let shopItemsData = [
  {
    id: "P001",
    name: "Mobile Phone",
    price: 15000,
    desc: "Mobile Phone - Level 1",
    img: "../../assets/images/mobile-phone.png",
  },
  {
    id: "P002",
    name: "Smart Watch",
    price: 5000,
    desc: "Smart Watch - Level 1",
    img: "../../assets/images/smart-watch.png",
  },
  {
    id: "P003",
    name: "Game Console",
    price: 10000,
    desc: "Game Console - Level 1",
    img: "../../assets/images/game-console.png",
  },
  {
    id: "P004",
    name: "Computer Mouse",
    price: 2000,
    desc: "Computer Mouse - Level 1",
    img: "../../assets/images/computer-mouse.png",
  },
  {
    id: "P005",
    name: "Camera",
    price: 20000,
    desc: "Camera - Level 2",
    img: "../../assets/images/camera.png",
  },
  {
    id: "P006",
    name: "Fridge",
    price: 25000,
    desc: "Fridge - Level 2",
    img: "../../assets/images/fridge.png",
  },
  {
    id: "P007",
    name: "Television",
    price: 35000,
    desc: "Television - Level 2",
    img: "../../assets/images/television.png",
  },
  {
    id: "P008",
    name: "Washing Machine",
    price: 23000,
    desc: "Washing Machine - Level 2",
    img: "../../assets/images/washing-machine.png",
  },
  {
    id: "P009",
    name: "Air Conditioner",
    price: 40000,
    desc: "Air Conditioner - Level 3",
    img: "../../assets/images/air-conditioner.png",
  },
  {
    id: "P010",
    name: "Laptop",
    price: 75000,
    desc: "Laptop - Level 3",
    img: "../../assets/images/laptop.png",
  },
  {
    id: "P011",
    name: "PC",
    price: 90000,
    desc: "PC - Level 3",
    img: "../../assets/images/computer.png",
  },
  {
    id: "P012",
    name: "iPad",
    price: 60000,
    desc: "iPad - Level 3",
    img: "../../assets/images/ipad.png",
  },
];
